"""add_upload_cycle_source_content

Revision ID: 1316c47e2e74
Revises: 8355f4b3f5a9
Create Date: 2026-02-19 21:04:32.935044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1316c47e2e74'
down_revision: Union[str, Sequence[str], None] = '8355f4b3f5a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_cycles', sa.Column('source_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_cycles', 'source_content')
    # ### end Alembic commands ###
